services:
  - type: web
    name: leaneage
    runtime: node
    buildCommand: npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: NODE_ENV
        value: production
