import Chapter01.definitions_ch1

set_option linter.all false

namespace Diestel
namespace Chapter01

universe u

/--
Diestel, Proposition 1.9.2.
Natural-language statement:
Together with the empty set, cuts form the cut space; this space is
generated by atomic cuts.
-/
axiom proposition_1_9_2 {V : Type u} (G : SimpleGraph V) [Fintype V] :
  (∀ D : EdgeSpace G,
    D ∈ cut_space G ↔
      ∃ cuts : List (Set G.edgeSet),
        (∀ F ∈ cuts, IsCut G F ∨ F = ∅) ∧
          D = cuts.foldr (fun F acc => edge_indicator G F + acc) 0) ∧
    cut_space G =
      Submodule.span (ZMod 2) {D : EdgeSpace G | ∃ v : V, D = edge_indicator G (atomic_cut G v)}

end Chapter01
end Diestel
